[package]
name = "client-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
arrayvec.workspace = true
async-trait = { workspace = true }
bitflags = { workspace = true, features = ["std"] }
game-core = { workspace = true }
runtime = { workspace = true }
